
services:
  order-service:
    build: ./order-service/
    container_name: order-service
    ports:
      - "8001:8001"
  
  payment-service:
    build: ./payment-service/
    container_name: payment-service
    ports:
      - "8002:8000"

  prometheus:
    image: ubuntu/prometheus:3-24.04_stable
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped